version: '3.6'

services:
  rmt-new-deposit:
    image: $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:$CI_COMMIT_BRANCH
    container_name: $APP-$CI_COMMIT_BRANCH
    env_file:
      - .env
    ports:
      - 9003:8080
    restart: always
